apiVersion: v1
kind: Service
metadata:
  name: order-status-api
  namespace: jenkins-cicd-lab
  labels:
    app.kubernetes.io/name: order-status-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: jenkins-cicd-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: order-status-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
